# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 15:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, default=b'', max_length=256, null=True, verbose_name='Brand')),
                ('model', models.CharField(blank=True, default=b'', max_length=256, null=True, verbose_name='Model')),
                ('car_reg', models.CharField(blank=True, default=None, max_length=16, null=True, verbose_name='Car reg. number')),
                ('vin', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='VIN number')),
                ('production_year', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Construction year')),
                ('first_registration_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='First Registration')),
                ('capicity', models.IntegerField(blank=True, default=None, null=True, verbose_name='cm3')),
                ('power', models.IntegerField(blank=True, default=None, null=True, verbose_name='KW')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Price')),
                ('type', models.CharField(blank=True, default=b'', max_length=16, null=True, verbose_name='Vehicle Category Name')),
                ('type_id', models.CharField(blank=True, default=b'', max_length=32, null=True, verbose_name='Vehicle Category id')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=8, null=True, verbose_name='Weight')),
                ('seats', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Seats')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('status', models.SmallIntegerField(blank=True, choices=[(1, 'Started to synchronize'), (2, 'Successfully synchronized'), (3, 'Error in synchronization')], default=1, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=None, max_length=32, verbose_name='Code')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('requested_reg_numbers', taggit.managers.TaggableManager(help_text='A comma-separated list of reg. numbers.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Car Reg. Number')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='com_local.Request'),
        ),
    ]
